export const EQUIPMENT_LIST = [
  "Engine # 01",
  "Engine # 02",
  "Engine # 03",
  "Engine # 04",
  "Engine # 05",
  "Radiator # 01",
  "Radiator # 02",
  "Radiator # 03",
  "Radiator # 04",
  "Radiator # 05",
  "Jetpuls Filter # 01",
  "Jetpuls Filter # 02",
  "Jetpuls Filter # 03",
  "Jetpuls Filter # 04",
  "Jetpuls Filter # 05",
  "Lube Oil Separator # 01",
  "Lube Oil Separator # 02",
  "Lube Oil Separator # 03",
  "Lube Oil Separator # 04",
  "Lube Oil Separator # 05",
  "HFO Separartor # 01",
  "HFO Separartor # 02",
  "HFO Separartor # 03",
  "HFO Separartor # 04",
  "SA compressor # 01",
  "SA compressor # 02",
  "SA compressor # 03",
  "Inst Air comp # 01",
  "Inst Air comp # 02",
  "Inst Air comp # 03",
  "Black Start Genset VOLVO",
  "EGB # 1",
  "EGB # 2",
  "EGB # 4",
  "EGB # 5",
  "Aux. Boiler (Oil Fired)  3ton",
  "Aux. Boiler (Oil Fired) 5ton",
  "Boiler feed water pump # 1",
  "Boiler feed water pump # 2",
  "Boiler feed water pump # 3",
  "Boiler feed water pump # 4",
  "Fire Fighting Jocky pump",
  "Electric driven pump",
  "Engine Driven pump",
  "RO # 1",
  "RO # 2",
  "RO # 3",
  "RAW water Turbines",
  "HFO decanting Pump 1~ 3",
  "HFO Storage tanks",
  "LFO decanting Pump 1~ 2",
  "Supply air fan # 1",
  "Supply air fan # 2",
  "Supply air fan # 3",
  "Supply air fan # 4",
  "Supply air fan # 5",
  "Aux supply air fan # 1",
  "Aux supply air fan # 2",
  "Aux supply air fan # 3",
  "Aux supply air fan # 4",
  "Aux supply air fan # 5",
  "HFO Feeder 1 Pump # 01",
  "HFO Feeder 1 Pump # 02",
  "HFO Feeder 2 Pump # 01",
  "HFO Feeder 2 Pump # 02",
  "LFO Feeder 1 Pump # 01",
  "LFO Feeder 2 Pump # 01",
  "LFO Feeder 2 Pump # 02",
  "Hydrophore Unit 1",
  "Hydrophore Unit 2",
  "HFO Transfer Pump # 01",
  "HFO Transfer Pump # 02",
  "Other",
];
